### ISSUE TITLE
Specify license in front page

### ISSUE THREAD

**Issue by ofirnk** [Manfred73/graphite-monitor-example#1]
Hey @Manfred73 ,

_Loved your examples._

#### Could you please specify a license in front page?

Thanks

**Comment by Manfred73** [comment]
Hi @ofirnk ,

Could you tell me what exactly do I need to put there?

Regards,
Manfred

**Comment by ofirnk** [comment]
Sure, see [this](https://help.github.com/articles/adding-a-license-to-a-repository/) from _Github help_.
Most permissive license is _Apache License V2_, but it's of course up to you to choose :)
https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by Manfred73** [comment]
Thanks for the notification, Added the LICENSE file.
